### ISSUE TITLE
value of type 'Self' has no member 'hopped'

### ISSUE THREAD

**Issue by jhoughjr** [madsodgaard/vapor-auth-template#1]
/Users/jimmyhoughjr/vapor-auth-template/Sources/App/Jobs/EmailJob.swift:47:14: Value of type 'Self' has no member 'hopped'

I ran swift package update then swift build in command line. Then built in Xcode with the same error.

**Comment by jhoughjr** [comment]
I wonder if ```
        // Mailgun
        .package(url: "https://github.com/vapor-community/VaporMailgunService.git", .branch("mads-updates")) ``` is related?

**Comment by madsodgaard** [comment]
Hey! Yea sorry about that, made some changes to that Mailgun branch which I forgot to update here. This has been fixed in #2 - basically you need to use `.delegating(to: EventLoop)` instead of `hopped(to: )`

**Comment by jhoughjr** [comment]
thanks for the quick fix. I'll pull again and test soon.

**Comment by jhoughjr** [comment]
works.
