### ISSUE TITLE
Docker files update to work with current documentation.

### ISSUE THREAD

**Issue by jhoughjr** [madsodgaard/vapor-auth-template#10]
Having issues with the existing dockerfiles and getting my app dockerized on a droplet,
I've confirmed vapor-beta's template works with my configuration following the docs.
Some images are different.

**Comment by madsodgaard** [comment]
The `Dockerfile` and `docker-compose.yml` should probably be updated to those at: https://github.com/vapor/template

**Comment by jhoughjr** [comment]
Ive dabbled with this and started work on it but havnt tested it yet.
I cam try this weekend to get a PR in unless someone else wants to.
