### ISSUE TITLE
Using Log Level Debug shows too many redis connections

### ISSUE THREAD

**Issue by jhoughjr** [madsodgaard/vapor-auth-template#12]
If you enable log level debug, the template as is does not configure the queue for refreshInterval.
In my app this caused 10Hz of redis messages making debugging impossible.
I've tested a fix

    app.queues.configuration.refreshInterval = .minutes(2)

or something reasonable resolves the issues making other logs visible and decluttering the log.

**Comment by madsodgaard** [comment]
I am not sure if this is something I want to add to the template. It's a configuration issue, so it's up to the user to actually configure the refresh interval and the respective logging levels. I think we should leave it as is, and let the user decide whether to change it or not.

Also, this issue only occurs when you run the queues worker in process with your main Vapor application. Which is not recommended in production. So you can just comment out the `startInProccessWorkers()` call when debugging your application or alternatively changing the refresh interval.

**Comment by jhoughjr** [comment]
My opinion is there is absolutely nothing that indicates to someone that they need to configure the refresh interval.
Considering its sending emails and that is part of the templates advertised functionality it should do something other then thrash redis multiple times per second

Perhaps an assertion that it has been configured.
Or ar least mention of it in the docs.
Especially for the purpose of email verification 2 mins is a good balance of fast response with thrashing redis.

**Comment by jhoughjr** [comment]
I do wonder how the refresh interval would behave at scale. That could be a reason to poll faster.
