### ISSUE TITLE
Tests broken?

### ISSUE THREAD

**Issue by jhoughjr** [madsodgaard/vapor-auth-template#15]
For about 2 weeks roughly,Test Suite 'All tests' failed at 2020-09-24 10:25:12.905.
	 Executed 43 tests, with 18 tests skipped and 37 failures (37 unexpected) in 3.790 (3.794) seconds
I suspect it is due to deps changing or something.
I've been trying to fix them off and on, without success.

**Comment by madsodgaard** [comment]
All tests are green for me on the latest version, this is probably a local issue due to specific configuration.

Can you confirm @jhoughjr ?
