### ISSUE TITLE
Thread 1: Fatal error: Failed to load JWKS Keypair file at

### ISSUE THREAD

**Issue by sinduke** [madsodgaard/vapor-auth-template#16]
Thread 1: Fatal error: Failed to load JWKS Keypair file at: /Users/kh/vapor-auth-template/keypair.jwks
![image](https://user-images.githubusercontent.com/22930750/103332517-3689ec80-4aa5-11eb-897e-c1de7dc7cf18.png)

**Comment by madsodgaard** [comment]
You need to generate a JWKS keypair (you can do so at [https://mkjwk.org](url))
Then place that file in the root directory and name it keypair.jwks or set environment variable JWKS_KEYPAIR_FILE

**Comment by sinduke** [comment]
Thanks
