### ISSUE TITLE
Registration verification sequence

### ISSUE THREAD

**Issue by VineFiner** [madsodgaard/vapor-auth-template#5]
We know that hash is a time-consuming operation, why not first confirm whether there is a user?

```
        return User.query(on: req.db)
            .filter(\.$email == registerRequest.email)
            .first()
            .flatMap { (result) -> EventLoopFuture<Void> in
                if let _ = result {
                    return req.eventLoop.makeFailedFuture(AuthenticationError.emailAlreadyExists)
                }
                do {
                    let user = try User(from: registerRequest, hash: Bcrypt.hash(registerRequest.password))
                    return user.save(on: req.db)
                        .flatMap { (void) -> EventLoopFuture<Void> in
                        return req.emailVerifier.verify(for: user)
                    }
                } catch {
                    return req.eventLoop.makeFailedFuture(error)
                }
        }
        .transform(to: .created)
```

**Comment by madsodgaard** [comment]
This could leave to a race condition, therefore we let the database decide whether a constraint exists or not. On top that the hash is performed on a background thread, and not blocking the eventlop. It just adds time complexity to that request (think bcrypt is about 100-200ms?)

**Comment by VineFiner** [comment]
> This could leave to a race condition, therefore we let the database decide whether a constraint exists or not. On top that the hash is performed on a background thread, and not blocking the eventlop. It just adds time complexity to that request (think bcrypt is about 100-200ms?)


You are right, the proportion of existing users of the registered interface is not large.
