### ISSUE TITLE
UserRepository prevents build

### ISSUE THREAD

**Issue by jhoughjr** [madsodgaard/vapor-auth-template#8]
I get 4 errors out of the box,
Undeclared type FieldProtocol
and Value is not a member of type Field.

In UserRepository.swift

**Comment by jhoughjr** [comment]
Might have been broken with this PR, idk.
https://github.com/vapor/fluent-kit/pull/268/commits/c8d67d944ed5a0275665a63f37ab06c91dd49991

**Comment by madsodgaard** [comment]
Fixed in #9
